export const FETCH_GIFS = 'FETCH_GIFS';
export const LOAD_GIFS = 'LOAD_GIFS';
export const INIT_LOAD_MORE_GIFS = 'INIT_LOAD_MORE_GIFS';
export const LOAD_MORE_GIFS = 'LOAD_MORE_GIFS';
export const LOAD_GIFS_FAILED = 'LOAD_GIFS_FAILED';

export const GET_GIF = 'GET_GIF';
export const CLEAR_LOADED_GIF = 'CLEAR_LOADED_GIF';
export const LOAD_SINGLE_GIF = 'LOAD_SINGLE_GIF';
export const LOAD_SINGLE_GIF_FAILED = 'LOAD_SINGLE_GIF_FAILED';

export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS';
export const INIT_LOAD_MORE_SEARCH_RESULTS = 'INIT_LOAD_MORE_SEARCH_RESULTS';
export const LOAD_MORE_SEARCH_RESULTS = 'LOAD_MORE_SEARCH_RESULTS';
export const LOAD_SEARCH_RESULTS_FAILED = 'LOAD_SEARCH_RESULTS_FAILED';